In [12]:
import pandas as pd
import numpy as np
df = pd.read_csv('netflix_titles.csv')

In [17]:
df.shape

(8807, 12)

In [18]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [21]:
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

In [22]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [26]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [27]:
#include all
df.describe(include='all')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
count,8807,8807,8807,6173,7982,7976,8797,8807.000000,8803,8804,8807,8807
unique,8807,2,8807,4528,7692,748,1767,NaN,17,220,514,8775
top,s8807,Movie,Zubaan,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",NaN,TV-MA,1 Season,"Dramas, International Movies","Paranormal activity at a lush, abandoned prope..."
freq,1,6131,1,19,19,2818,109,NaN,3207,1793,362,4
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.180198,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.819312,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1925.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,NaN,NaN

In [28]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [29]:
# in percentage
(df.isnull().sum()/len(df))*100

show_id          0.000000
type             0.000000
title            0.000000
director        29.908028
cast             9.367549
country          9.435676
date_added       0.113546
release_year     0.000000
rating           0.045418
duration         0.034064
listed_in        0.000000
description      0.000000
dtype: float64

In [30]:
# Duplicates rows
df.duplicated().sum()

np.int64(0)

In [34]:
#remove duplicates 
df.drop_duplicates(inplace=True)

In [36]:
#Check DATATYPES
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [38]:
# Remove Extra Spaces
string_cols = df.select_dtypes(include='object').columns

In [39]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [40]:
# Missing Value Treatment
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [42]:
## Convert Date Column
df['date_added'].head()

0    September 25, 2021
1    September 24, 2021
2    September 24, 2021
3    September 24, 2021
4    September 24, 2021
Name: date_added, dtype: object

In [43]:
df['date_added'].dtype

dtype('O')

In [46]:
# Unique Values
df['rating'].unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', '74 min', '84 min', '66 min', 'NR', nan,
       'TV-Y7-FV', 'UR'], dtype=object)

In [47]:
df['rating'].nunique()

17

In [48]:
df['country'].unique()

array(['United States', 'South Africa', nan, 'India',
       'United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia',
       'United Kingdom', 'Germany, Czech Republic', 'Mexico', 'Turkey',
       'Australia', 'United States, India, France', 'Finland',
       'China, Canada, United States',
       'South Africa, United States, Japan', 'Nigeria', 'Japan',
       'Spain, United States', 'France', 'Belgium',
       'United Kingdom, United States', 'United States, United Kingdom',
       'France, United States', 'South Korea', 'Spain',
       'United States, Singapore', 'United Kingdom, Australia, France',
       'United Kingdom, Australia, France, United States',
       'United States, Canada', 'Germany, United States',
       'South Africa, United States', 'United States, Mexico',
       'United States, Italy, France, Japan',
       'United States, Italy, Romania, United Kingdom',
       'Australia, United States', 'Argentina, Venezuela',
       'United States, United Kingdom, Canada', 'China, Hong Kong',
       'Russia', 'Canada', 'Hong Kong', 'United States, China, Hong Kong',
       'Italy, United States', 'United States, Germany',
       'United Kingdom, Canada, United States', ', South Korea',
       'Ireland', 'India, Nepal',
       'New Zealand, Australia, France, United States', 'Italy',
       'Italy, Brazil, Greece', 'Argentina', 'Jordan', 'Colombia',
       'United States, Japan', 'Belgium, United Kingdom',
       'Switzerland, United Kingdom, Australia', 'Israel, United States',
       'Canada, United States', 'Brazil', 'Argentina, Spain', 'Taiwan',
       'United States, Nigeria', 'Bulgaria, United States',
       'Spain, United Kingdom, United States', 'United States, China',
       'United States, France',
       'Spain, France, United Kingdom, United States',
       ', France, Algeria', 'Poland', 'Germany',
       'France, Israel, Germany, United States, United Kingdom',
       'New Zealand', 'Saudi Arabia', 'Thailand', 'Indonesia',
       'Egypt, Denmark, Germany', 'United States, Switzerland',
       'Hong Kong, Canada, United States', 'Kuwait, United States',
       'France, Canada, United States, Spain',
       'France, Netherlands, Singapore', 'France, Belgium',
       'Ireland, United States, United Kingdom', 'Egypt', 'Malaysia',
       'Israel', 'Australia, New Zealand', 'United Kingdom, Germany',
       'Belgium, Netherlands', 'South Korea, Czech Republic',
       'Australia, Germany', 'Vietnam', 'United Kingdom, Belgium',
       'United Kingdom, Australia, United States',
       'France, Japan, United States',
       'United Kingdom, Germany, Spain, United States',
       'United Kingdom, United States, France, Italy',
       'United States, Germany, Canada',
       'United States, France, Italy, United Kingdom',
       'United States, United Kingdom, Germany, Hungary',
       'United States, New Zealand', 'Sweden', 'China', 'Lebanon',
       'Romania', 'Finland, Germany', 'Lebanon, Syria', 'Philippines',
       'Iceland', 'Denmark', 'United States, India',
       'Philippines, Singapore, Indonesia',
       'China, United States, Canada', 'Lebanon, United Arab Emirates',
       'Canada, United States, Denmark', 'United Arab Emirates',
       'Mexico, France, Colombia', 'Netherlands',
       'Germany, United States, France', 'United States, Bulgaria',
       'United Kingdom, France, Germany, United States',
       'Norway, Denmark', 'Syria, France, Lebanon, Qatar',
       'United States, Czech Republic', 'Mauritius',
       'Canada, South Africa', 'Austria', 'Mexico, Brazil',
       'Germany, France', 'Mexico, United States',
       'United Kingdom, France, Spain, United States',
       'United States, Australia',
       'United States, United Kingdom, France', 'United States, Russia',
       'United States, United Kingdom, New Zealand',
       'Australia, United Kingdom', 'Canada, Nigeria, United States',
       'France, United States, United Kingdom, Canada',
       'France, United Kingdom', 'India, United Kingdom',
       'Canada, United States, Mexico',
       'United Kingdom, Germany, United States',
       'Czech Republic, United Kingdom, United States',
       'China, United Kingdom', 'Italy, United Kingdom', 'China, Taiwan',
       'United States, Brazil, Japan, Spain, India',
       'United States, China, United Kingdom', 'Cameroon',
       'Lebanon, Palestine, Denmark, Qatar', 'Japan, United States',
       'Uruguay, Germany', 'Egypt, Saudi Arabia',
       'United Kingdom, France, Poland, Germany, United States',
       'Ireland, Switzerland, United Kingdom, France, United States',
       'United Kingdom, South Africa, France',
       'Ireland, United Kingdom, France, Germany',
       'Russia, United States', 'United Kingdom, United States, France',
       'United Kingdom,', 'United States, India, United Kingdom', 'Kenya',
       'Spain, Argentina', 'India, United Kingdom, France, Qatar',
       'Belgium, France', 'Argentina, Chile', 'United States, Thailand',
       'Chile, Brazil', 'United States, Colombia',
       'Canada, United States, United Kingdom', 'Uruguay', 'Luxembourg',
       'United States, Cambodia, Romania', 'Bangladesh',
       'Spain, Belgium, United States',
       'United Kingdom, United States, Australia',
       'Canada, United States, France', 'Portugal, United States',
       'Portugal, Spain', 'India, United States',
       'United Kingdom, Ireland', 'United Kingdom, Spain, United States',
       'Hungary, United States', 'United States, South Korea',
       'Canada, United States, Cayman Islands', 'India, France',
       'France, Canada', 'Canada, Hungary, United States', 'Norway',
       'Canada, United Kingdom, United States',
       'United Kingdom, Germany, France, United States',
       'Denmark, United States', 'Senegal', 'France, Algeria',
       'United Kingdom, Finland, Germany, United States, Australia, Japan, France, Ireland',
       'Philippines, Canada, United Kingdom, United States',
       'Ireland, France, Iceland, United States, Mexico, Belgium, United Kingdom, Hong Kong',
       'Singapore', 'Kuwait', 'United States, France, Serbia',
       'United States, Italy', 'Spain, Italy',
       'United States, Ireland, United Kingdom, India',
       'United Kingdom, Singapore', 'Hong Kong, United States',
       'United States, Malta, France, United Kingdom',
       'United States, China, Canada', 'Canada, United States, Ireland',
       'Lebanon, Canada, France', 'Japan, Canada, United States',
       'Spain, France, Canada',
       'Denmark, Singapore, Canada, United States',
       'United States, France, Denmark', 'United States, China, Colombia',
       'Spain, Thailand, United States', 'Mexico, Spain',
       'Ireland, Luxembourg, Belgium', 'China, United States',
       'Canada, Belgium', 'Canada, United Kingdom',
       'Lebanon, United Arab Emirates, France, Switzerland, Germany',
       'France, Belgium, Italy',
       'Lebanon, United States, United Arab Emirates', 'Lebanon, France',
       'France, Lebanon', 'France, Lebanon, United Kingdom',
       'France, Norway, Lebanon, Belgium',
       'Sweden, Czech Republic, United Kingdom, Denmark, Netherlands',
       'United States, United Kingdom, India', 'Indonesia, Netherlands',
       'Turkey, South Korea', 'Serbia, United States', 'Namibia',
       'United Kingdom, Kenya', 'United Kingdom, France, Germany, Spain',
       'United Kingdom, France, United States, Belgium, Luxembourg, China, Germany',
       'Thailand, United States',
       'United States, France, Canada, Belgium', 'United Kingdom, China',
       'Germany, China, United Kingdom',
       'Australia, New Zealand, United States',
       'Hong Kong, Iceland, United States', 'France, Australia, Germany',
       'United States, Belgium, Canada, France', 'South Africa, Angola',
       'United States, Philippines',
       'United States, United Kingdom, Canada, China',
       'United States, Canada, United Kingdom', 'Turkey, United States',
       'Peru, Germany, Norway', 'Mozambique', 'Brazil, France',
       'China, Spain, South Korea, United States', 'Spain, Germany',
       'Hong Kong, China', 'France, Belgium, Luxembourg, Cambodia,',
       'United Kingdom, Australia', 'Belarus',
       'Indonesia, United Kingdom',
       'Switzerland, France, Belgium, United States', 'Ghana',
       'Spain, France, Canada, United States', 'Chile, Italy',
       'United Kingdom, Nigeria', 'Chile', 'France, Egypt',
       'Egypt, France', 'France, Brazil, Spain, Belgium',
       'Egypt, Algeria', 'Canada, South Korea, United States',
       'Nigeria, United Kingdom', 'United States, France, Canada',
       'Poland, United States',
       'United Arab Emirates, Jordan, Lebanon, Saudi Arabia',
       'United States, Mexico, Spain, Malta',
       'Saudi Arabia, United Arab Emirates', 'Zimbabwe',
       'United Kingdom, Germany, United Arab Emirates, New Zealand',
       'Romania, United States', 'Canada, Nigeria',
       'Saudi Arabia, Netherlands, Germany, Jordan, United Arab Emirates, United States',
       'United Kingdom, Spain', 'Finland, France',
       'United Kingdom, Germany, United States, France',
       'India, United Kingdom, China, Canada, Japan, South Korea, United States',
       'Italy, United Kingdom, France', 'United States, Mexico, Colombia',
       'Turkey, India', 'Italy, Turkey',
       'United Kingdom, United States, Japan',
       'France, Belgium, United States',
       'Puerto Rico, United States, Colombia', 'Uruguay, Argentina',
       'United States, United Kingdom, Japan', 'United States, Argentina',
       'United Kingdom, Italy', 'Ireland, United Kingdom',
       'United Kingdom, France, Belgium, Canada, United States',
       'Netherlands, Germany, Denmark, United Kingdom', 'Hungary',
       'Austria, Germany', 'Taiwan, China',
       'United Kingdom, United States, Ireland',
       'South Korea, United States', 'Brazil, United Kingdom',
       'Pakistan, United States', 'Romania, France, Switzerland, Germany',
       'Romania, United Kingdom', 'France, Malta, United States',
       'Cyprus',
       'United Kingdom, France, Belgium, Ireland, United States',
       'United States, Norway, Canada', 'Kenya, United States',
       'France, South Korea, Japan, United States', 'Taiwan, Malaysia',
       'Uruguay, Argentina, Germany, Spain',
       'United States, United Kingdom, France, Germany, Japan',
       'United States, France, Japan',
       'United Kingdom, France, United States',
       'Spain, France, United States',
       'Indonesia, South Korea, Singapore', 'United States, Spain',
       'Netherlands, Germany, Italy, Canada',
       'Spain, Germany, Denmark, United States', 'Norway, Sweden',
       'South Korea, Canada, United States, China',
       'Argentina, Uruguay, Serbia', 'France, Japan',
       'Mauritius, South Africa', 'United States, Poland',
       'United Kingdom, United States, Germany, Denmark, Belgium, Japan',
       'India, Germany', 'India, United Kingdom, Canada, United States',
       'Philippines, United States', 'Romania, Bulgaria, Hungary',
       'Uruguay, Guatemala', 'France, Senegal, Belgium',
       'United Kingdom, Canada', 'Mexico, United States, Spain, Colombia',
       'Canada, Norway', 'Singapore, United States',
       'Finland, Germany, Belgium', 'United Kingdom, France',
       'United States, Chile', 'United Kingdom, Japan, United States',
       'Spain, United Kingdom', 'Argentina, United States, Mexico',
       'United States, South Korea, Japan', 'Canada, Australia',
       'United Kingdom, Hungary, Australia', 'Italy, Belgium',
       'United States, United Kingdom, Germany', 'Switzerland',
       'Singapore, Malaysia',
       'France, Belgium, Luxembourg, Romania, Canada, United States',
       'South Africa, Nigeria', 'Spain, France',
       'United Kingdom, Hong Kong', 'Pakistan', 'Brazil, United States',
       'Denmark, Brazil, France, Portugal, Sweden', 'India, Turkey',
       'Malaysia, Singapore, Hong Kong', 'Philippines, Singapore',
       'Australia, Canada', 'Taiwan, China, France, United States',
       'Germany, Italy', 'Colombia, Peru, United Kingdom',
       'Thailand, China, United States', 'Argentina, United States',
       'Sweden, United States', 'Uruguay, Spain, Mexico',
       'France, Luxembourg, Canada', 'Denmark, Spain', 'Chile, Argentina',
       'United Kingdom, Belgium, Sweden', 'Canada, Brazil',
       'Italy, France', 'Canada, Germany',
       'Pakistan, United Arab Emirates', 'Ghana, United States',
       'Mexico, Finland', 'United Arab Emirates, United Kingdom, India',
       'Netherlands, Belgium', 'United States, Taiwan',
       'Austria, Iraq, United States', 'United Kingdom, Malawi',
       'Paraguay, Argentina', 'United Kingdom, Russia, United States',
       'India, Pakistan', 'Indonesia, Singapore', 'Spain, Belgium',
       'Iceland, Sweden, Belgium', 'Croatia', 'Uruguay, Argentina, Spain',
       'United Kingdom, Ireland, United States',
       'Canada, Germany, France, United States', 'United Kingdom, Japan',
       'Norway, Denmark, Netherlands, Sweden',
       'Hong Kong, China, United States', 'Ireland, Canada',
       'Italy, Switzerland, France, Germany', 'Mexico, Netherlands',
       'United States, Sweden', 'Germany, France, Russia',
       'France, Iran, United States', 'United Kingdom, India',
       'Russia, Poland, Serbia', 'Spain, Portugal', 'Peru',
       'Mexico, Argentina',
       'United Kingdom, Canada, United States, Cayman Islands',
       'Indonesia, United States',
       'United States, Israel, United Kingdom, Canada',
       'Norway, Iceland, United States', 'Czech Republic, United States',
       'United Kingdom, India, United States',
       'United Kingdom, West Germany', 'India, Australia',
       'United States,', 'Belgium, United Kingdom, United States',
       'India, Germany, Austria',
       'United States, Brazil, South Korea, Mexico, Japan, Germany',
       'Spain, Mexico', 'China, Japan', 'Argentina, France',
       'China, United States, United Kingdom',
       'France, Luxembourg, United States',
       'China, United States, Australia', 'Colombia, Mexico',
       'United States, Canada, Ireland', 'Chile, Peru',
       'Argentina, Italy', 'Canada, Japan, United States',
       'United Kingdom, Canada, United States, Germany',
       'Italy, Switzerland, Albania, Poland',
       'United States, Japan, Canada', 'Cambodia',
       'Italy, United States, Argentina',
       'Saudi Arabia, Syria, Egypt, Lebanon, Kuwait',
       'United States, Canada, Indonesia, United Kingdom, China, Singapore',
       'Spain, Colombia',
       'United Kingdom, South Africa, Australia, United States',
       'Bulgaria', 'Argentina, Brazil, France, Poland, Germany, Denmark',
       'United Kingdom, Spain, United States, Germany',
       'Philippines, Qatar', 'Netherlands, Belgium, Germany, Jordan',
       'United Arab Emirates, United States', 'Norway, Germany, Sweden',
       'South Korea, China', 'Georgia', 'Soviet Union, India',
       'Australia, United Arab Emirates', 'Canada, Germany, South Africa',
       'South Korea, China, United States', 'India, Soviet Union',
       'India, Mexico', 'Georgia, Germany, France',
       'United Arab Emirates, Romania', 'India, Malaysia',
       'Germany, Jordan, Netherlands', 'Turkey, France, Germany, Poland',
       'Greece, United States', 'France, United Kingdom, United States',
       'Norway, Germany', 'France, Morocco', 'Cambodia, United States',
       'United States, Denmark', 'United States, Colombia, Mexico',
       'United Kingdom, Italy, Israel, Peru, United States',
       'Argentina, Uruguay, Spain, France',
       'United Kingdom, France, United States, Belgium',
       'France, Canada, China, Cambodia',
       'United Kingdom, France, Belgium, United States', 'Chile, France',
       'Netherlands, United States', 'France, United Kingdom, India',
       'Czech Republic, Slovakia', 'Singapore, France',
       'Spain, Switzerland', 'United States, Australia, China',
       'South Africa, United States, Germany',
       'United States, United Kingdom, Australia',
       'Spain, Italy, Argentina', 'Chile, Spain, Argentina, Germany',
       'West Germany', 'Austria, Czech Republic', 'Lebanon, Qatar',
       'United Kingdom, Jordan, Qatar, Iran',
       'France, South Korea, Japan', 'Israel, Germany, France',
       'Canada, Japan, Netherlands', 'United States, Hungary',
       'France, Germany', 'France, Qatar',
       'United Kingdom, Germany, Canada', 'Ireland, South Africa',
       'Chile, United States, France', 'Belgium, France, Netherlands',
       'United Kingdom, Ukraine, United States',
       'Germany, Australia, France, China', 'Norway, United States',
       'United States, Bermuda, Ecuador',
       'United States, Hungary, Ireland, Canada',
       'United Kingdom, Egypt, United States',
       'United States, France, United Kingdom', 'Spain, Mexico, France',
       'United States, South Africa', 'Hong Kong, China, Singapore',
       'South Africa, China, United States', 'Denmark, France, Poland',
       'New Zealand, United Kingdom',
       'Netherlands, Denmark, South Africa', 'Iran, France',
       'United Kingdom, United States, France, Germany',
       'Australia, France', 'Ireland, United Kingdom, United States',
       'United Kingdom, France, Germany', 'Canada, Luxembourg',
       'Brazil, Netherlands, United States, Colombia, Austria, Germany',
       'France, Canada, Belgium', 'Canada, France',
       'Bulgaria, United States, Spain, Canada', 'Sweden, Netherlands',
       'France, United States, Mexico',
       'Australia, United Kingdom, United Arab Emirates, Canada',
       'Australia, Armenia, Japan, Jordan, Mexico, Mongolia, New Zealand, Philippines, South Africa, Sweden, United States, Uruguay',
       'India, Iran', 'France, Belgium, Spain',
       'Denmark, Sweden, Israel, United States', 'United States, Iceland',
       'United Kingdom, Russia',
       'United States, Israel, Italy, South Africa',
       'Netherlands, Denmark, France, Germany', 'South Korea, Japan',
       'United Kingdom, Pakistan', 'France, New Zealand',
       'United Kingdom, Czech Republic, United States, Germany, Bahamas',
       'China, Germany, India, United States', 'Germany, Sri Lanka',
       'United States, India, Bangladesh',
       'United States, Canada, France', 'Brazil, France, Germany',
       'Germany, United States, Hong Kong, Singapore',
       'France, Germany, Switzerland',
       'Germany, France, Luxembourg, United Kingdom, United States',
       'United Kingdom, Canada, Italy', 'Czech Republic, France',
       'Taiwan, Hong Kong, United States, China', 'Germany, Australia',
       'United Kingdom, Poland, United States', 'Denmark, Zimbabwe',
       'United Kingdom, South Africa',
       'Finland, Sweden, Norway, Latvia, Germany',
       'South Africa, United States, New Zealand, Canada',
       'United States, Italy, United Kingdom, Liechtenstein',
       'Denmark, France, Belgium, Italy, Netherlands, United States, United Kingdom',
       'United States, Australia, Mexico',
       'United Kingdom, Czech Republic, Germany, United States',
       'France, China, Japan, United States',
       'United States, South Korea, China', 'Germany, Belgium',
       'Pakistan, Norway, United States',
       'United States, Canada, Belgium, United Kingdom', 'Venezuela',
       'Canada, France, Italy, Morocco, United States',
       'Canada, Spain, France', 'United States, Indonesia',
       'Spain, France, Italy',
       'United Arab Emirates, United States, United Kingdom',
       'United Kingdom, Israel, Russia', 'Spain, Cuba',
       'United States, Brazil', 'United States, France, Mexico',
       'United States, Nicaragua',
       'United Kingdom, United States, Spain, Germany, Greece, Canada',
       'Italy, Canada, France',
       'United Kingdom, Denmark, Canada, Croatia', 'Italy, Germany',

In [49]:
df['type'].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [50]:
df['listed_in'].unique()

array(['Documentaries', 'International TV Shows, TV Dramas, TV Mysteries',
       'Crime TV Shows, International TV Shows, TV Action & Adventure',
       'Docuseries, Reality TV',
       'International TV Shows, Romantic TV Shows, TV Comedies',
       'TV Dramas, TV Horror, TV Mysteries', 'Children & Family Movies',
       'Dramas, Independent Movies, International Movies',
       'British TV Shows, Reality TV', 'Comedies, Dramas',
       'Crime TV Shows, Docuseries, International TV Shows',
       'Dramas, International Movies',
       'Children & Family Movies, Comedies',
       'British TV Shows, Crime TV Shows, Docuseries',
       'TV Comedies, TV Dramas', 'Documentaries, International Movies',
       'Crime TV Shows, Spanish-Language TV Shows, TV Dramas',
       'Thrillers',
       'International TV Shows, Spanish-Language TV Shows, TV Action & Adventure',
       'International TV Shows, TV Action & Adventure, TV Dramas',
       'Comedies, International Movies',
       'Comedies, International Movies, Romantic Movies',
       'Docuseries, International TV Shows, Reality TV',
       'Comedies, International Movies, Music & Musicals', 'Comedies',
       'Horror Movies, Sci-Fi & Fantasy', 'TV Comedies',
       'British TV Shows, International TV Shows, TV Comedies',
       'International TV Shows, TV Dramas, TV Thrillers', "Kids' TV",
       'Dramas, International Movies, Thrillers',
       'Action & Adventure, Dramas, International Movies',
       "Kids' TV, TV Comedies", 'Action & Adventure, Dramas',
       "Kids' TV, TV Sci-Fi & Fantasy",
       'Action & Adventure, Classic Movies, Dramas',
       'Dramas, Horror Movies, Thrillers',
       'Action & Adventure, Horror Movies, Thrillers',
       'Action & Adventure', 'Dramas, Thrillers',
       'International TV Shows, TV Dramas',
       'International TV Shows, TV Dramas, TV Sci-Fi & Fantasy',
       'Action & Adventure, Anime Features, International Movies',
       'Reality TV', 'Docuseries, International TV Shows',
       'Documentaries, International Movies, Sports Movies',
       'International TV Shows, Reality TV, Romantic TV Shows',
       'British TV Shows, Docuseries, International TV Shows',
       'Anime Series, International TV Shows',
       'Comedies, Dramas, International Movies',
       'Crime TV Shows, TV Comedies, TV Dramas',
       'Action & Adventure, Comedies, Dramas', "Anime Series, Kids' TV",
       'International Movies, Thrillers', "Kids' TV, Korean TV Shows",
       'Documentaries, Sports Movies', 'Sci-Fi & Fantasy, Thrillers',
       'Dramas, International Movies, Romantic Movies',
       'Documentaries, Music & Musicals',
       "Kids' TV, TV Comedies, TV Sci-Fi & Fantasy",
       "British TV Shows, Kids' TV", 'Docuseries, Science & Nature TV',
       'Children & Family Movies, Dramas',
       "Kids' TV, TV Dramas, Teen TV Shows",
       'Crime TV Shows, International TV Shows, Spanish-Language TV Shows',
       'Docuseries, International TV Shows, Spanish-Language TV Shows',
       'Dramas', 'Comedies, Romantic Movies', 'Dramas, Romantic Movies',
       'Comedies, Dramas, Independent Movies',
       'Crime TV Shows, TV Action & Adventure, TV Comedies',
       'Children & Family Movies, Music & Musicals',
       'Action & Adventure, Classic Movies, Cult Movies',
       'International TV Shows, TV Action & Adventure, TV Comedies',
       'Action & Adventure, Sci-Fi & Fantasy',
       'Action & Adventure, Comedies', 'Classic Movies, Comedies, Dramas',
       'Comedies, Cult Movies', 'Comedies, Cult Movies, Music & Musicals',
       'Comedies, Music & Musicals', 'TV Shows',
       'Action & Adventure, International Movies',
       'Anime Series, International TV Shows, Teen TV Shows',
       'Action & Adventure, Children & Family Movies, Cult Movies',
       'Comedies, Dramas, Romantic Movies',
       'Comedies, Cult Movies, Sci-Fi & Fantasy',
       'Classic Movies, Dramas',
       'Action & Adventure, Children & Family Movies, Comedies',
       'Dramas, Faith & Spirituality', 'Documentaries, LGBTQ Movies',
       'Action & Adventure, Classic Movies', 'Docuseries',
       'International TV Shows, TV Comedies',
       'Dramas, Independent Movies',
       'Action & Adventure, Comedies, International Movies',
       'International TV Shows, Spanish-Language TV Shows, TV Dramas',
       'Crime TV Shows, International TV Shows, TV Dramas',
       'Action & Adventure, Horror Movies, International Movies',
       'Comedies, International Movies, Sci-Fi & Fantasy',
       'Action & Adventure, International Movies, Music & Musicals',
       'Dramas, International Movies, Music & Musicals',
       'Horror Movies, International Movies', 'Reality TV, Teen TV Shows',
       'Crime TV Shows, TV Dramas, TV Mysteries',
       'International TV Shows, Reality TV',
       'International TV Shows, TV Comedies, TV Dramas',
       'Dramas, Independent Movies, Romantic Movies', 'Horror Movies',
       'Documentaries, LGBTQ Movies, Sports Movies',
       'Horror Movies, International Movies, Thrillers',
       'Action & Adventure, Anime Features',
       'TV Dramas, TV Mysteries, TV Sci-Fi & Fantasy',
       'International TV Shows, Spanish-Language TV Shows, TV Comedies',
       'Children & Family Movies, Comedies, Music & Musicals',
       'Comedies, Independent Movies',
       'Anime Series, International TV Shows, Romantic TV Shows',
       'Classic Movies, Dramas, Independent Movies',
       'International TV Shows, Romantic TV Shows, Spanish-Language TV Shows',
       'International TV Shows, TV Dramas, Teen TV Shows',
       'Stand-Up Comedy',
       'Action & Adventure, Anime Features, Children & Family Movies',
       'International TV Shows, Romantic TV Shows, TV Dramas',
       'International Movies, Music & Musicals',
       'TV Action & Adventure, TV Dramas, TV Mysteries',
       'Horror Movies, Independent Movies, International Movies',
       'Comedies, Cult Movies, International Movies',
       'Classic Movies, Dramas, International Movies', 'Movies',
       'Crime TV Shows, Docuseries',
       'Children & Family Movies, Comedies, Sci-Fi & Fantasy',
       'Anime Series, International TV Shows, TV Thrillers',
       'Action & Adventure, Horror Movies, Sci-Fi & Fantasy',
       'Classic Movies, Comedies, Cult Movies',
       'TV Dramas, Teen TV Shows',
       'Action & Adventure, Sci-Fi & Fantasy, Thrillers',
       'Children & Family Movies, Comedies, Dramas',
       'Dramas, Sports Movies',
       'Action & Adventure, Dramas, Sci-Fi & Fantasy',
       'Action & Adventure, Comedies, Cult Movies',
       'Dramas, Independent Movies, Thrillers',
       'TV Dramas, TV Sci-Fi & Fantasy',
       'Action & Adventure, International Movies, Thrillers',
       'British TV Shows, International TV Shows, Reality TV',
       'TV Action & Adventure, TV Dramas, Teen TV Shows', 'Anime Series',
       'Crime TV Shows, TV Action & Adventure, TV Sci-Fi & Fantasy',
       'Crime TV Shows, International TV Shows, TV Comedies',
       'Stand-Up Comedy & Talk Shows, TV Comedies',
       'Classic & Cult TV, TV Action & Adventure, TV Dramas',
       'Children & Family Movies, Sports Movies',
       'TV Action & Adventure, TV Sci-Fi & Fantasy',
       'Anime Series, Stand-Up Comedy & Talk Shows', 'TV Dramas',
       'Anime Features, Children & Family Movies, International Movies',
       'Classic & Cult TV, Crime TV Shows, International TV Shows',
       'Crime TV Shows, International TV Shows, Romantic TV Shows',
       'Horror Movies, LGBTQ Movies',
       'Action & Adventure, Dramas, Romantic Movies',
       'Documentaries, International Movies, Music & Musicals',
       'TV Comedies, TV Dramas, Teen TV Shows',
       'Children & Family Movies, Comedies, Sports Movies',
       'Children & Family Movies, Dramas, International Movies',
       'Comedies, Documentaries, International Movies',
       'Romantic TV Shows, TV Dramas',
       'Anime Series, TV Horror, TV Thrillers',
       'International Movies, Romantic Movies',
       'TV Action & Adventure, TV Dramas, TV Sci-Fi & Fantasy',
       "Kids' TV, Korean TV Shows, TV Comedies",
       'British TV Shows, Crime TV Shows, International TV Shows',
       'Crime TV Shows, TV Horror, TV Mysteries',
       'Docuseries, International TV Shows, Science & Nature TV',
       'British TV Shows, International TV Shows, TV Dramas',
       "Kids' TV, TV Action & Adventure, TV Sci-Fi & Fantasy",
       'International Movies, Romantic Movies, Thrillers',
       'Action & Adventure, Cult Movies, International Movies',
       'Action & Adventure, Comedies, Sci-Fi & Fantasy',
       "International TV Shows, Kids' TV, TV Mysteries",
       'Action & Adventure, Thrillers',
       'Dramas, Faith & Spirituality, International Movies',
       'Action & Adventure, Classic Movies, Comedies',
       'Action & Adventure, Comedies, Sports Movies',
       'Action & Adventure, Children & Family Movies, Classic Movies',
       'Action & Adventure, Children & Family Movies, Dramas',
       'Horror Movies, Thrillers', 'Action & Adventure, Romantic Movies',
       'Dramas, Romantic Movies, Sci-Fi & Fantasy',
       'Dramas, Music & Musicals, Romantic Movies',
       'Anime Series, Crime TV Shows, International TV Shows',
       'Reality TV, Romantic TV Shows',
       'International Movies, Music & Musicals, Romantic Movies',
       'Reality TV, TV Action & Adventure, TV Mysteries',
       'Crime TV Shows, TV Dramas',
       'International TV Shows, Reality TV, Spanish-Language TV Shows',
       'Crime TV Shows, TV Dramas, TV Thrillers',
       'British TV Shows, Docuseries',
       'International TV Shows, Korean TV Shows, TV Comedies',
       'Action & Adventure, Anime Features, Classic Movies',
       'TV Action & Adventure, TV Dramas, TV Horror',
       'Crime TV Shows, International TV Shows, TV Thrillers',
       'Anime Series, Crime TV Shows, TV Horror',
       'Anime Features, Documentaries', 'Comedies, Horror Movies',
       'International TV Shows, Spanish-Language TV Shows, Stand-Up Comedy & Talk Shows',
       'Children & Family Movies, Documentaries, International Movies',
       'Romantic TV Shows, TV Comedies, TV Dramas',
       'Dramas, Faith & Spirituality, Romantic Movies',
       'Dramas, Independent Movies, LGBTQ Movies',
       'Comedies, Independent Movies, LGBTQ Movies',
       'Action & Adventure, Cult Movies, Sci-Fi & Fantasy',
       'Cult Movies, Horror Movies',
       'Action & Adventure, Dramas, Sports Movies',
       'Anime Series, Romantic TV Shows, Teen TV Shows',
       'Dramas, International Movies, LGBTQ Movies',
       'Dramas, Romantic Movies, Thrillers',
       'Children & Family Movies, Dramas, Faith & Spirituality',
       'Dramas, International Movies, Sports Movies',
       'Action & Adventure, Horror Movies',
       'Documentaries, International Movies, LGBTQ Movies',
       'Dramas, Independent Movies, Sci-Fi & Fantasy',
       'Comedies, Independent Movies, International Movies',
       'Reality TV, TV Horror, TV Thrillers',
       'TV Action & Adventure, TV Horror, TV Sci-Fi & Fantasy',
       'International TV Shows, TV Horror, TV Sci-Fi & Fantasy',
       'Independent Movies, International Movies, Thrillers',
       'Independent Movies, Thrillers', 'Documentaries, Dramas',
       'Action & Adventure, Sports Movies',
       'Dramas, International Movies, Sci-Fi & Fantasy',
       'Comedies, Independent Movies, Romantic Movies',
       'Horror Movies, Romantic Movies, Sci-Fi & Fantasy',
       'International TV Shows, Stand-Up Comedy & Talk Shows',
       'Action & Adventure, Anime Features, Horror Movies',
       'Cult Movies, Dramas, Music & Musicals', 'TV Dramas, TV Thrillers',
       'Crime TV Shows, International TV Shows, Korean TV Shows',
       'TV Horror, TV Mysteries, TV Thrillers',
       'Comedies, Horror Movies, International Movies',
       'Crime TV Shows, Docuseries, TV Mysteries',
       'Comedies, International Movies, Sports Movies',
       'Classic Movies, Music & Musicals',
       'Reality TV, TV Comedies, TV Horror',
       'Children & Family Movies, Faith & Spirituality, Music & Musicals',
       'International TV Shows, Korean TV Shows, Stand-Up Comedy & Talk Shows',
       'Dramas, Music & Musicals',
       'Docuseries, Science & Nature TV, TV Action & Adventure',
       "British TV Shows, Kids' TV, TV Dramas",
       'International TV Shows, Korean TV Shows, Romantic TV Shows',
       'Horror Movies, Independent Movies',
       "Anime Series, Kids' TV, TV Action & Adventure",
       'Comedies, Dramas, Music & Musicals', 'TV Horror, Teen TV Shows',
       'Comedies, LGBTQ Movies, Thrillers',
       'Docuseries, Reality TV, Science & Nature TV',
       'Crime TV Shows, Spanish-Language TV Shows, TV Action & Adventure',
       'Romantic TV Shows, Teen TV Shows', 'TV Comedies, Teen TV Shows',
       'Romantic TV Shows, TV Dramas, Teen TV Shows',
       'Children & Family Movies, Sci-Fi & Fantasy',
       'Romantic TV Shows, TV Action & Adventure, TV Dramas',
       'Comedies, International Movies, LGBTQ Movies',
       'Dramas, Sci-Fi & Fantasy', "Kids' TV, TV Thrillers",
       'TV Action & Adventure, TV Comedies, TV Sci-Fi & Fantasy',
       'British TV Shows, Romantic TV Shows, TV Dramas',
       'Anime Series, International TV Shows, Spanish-Language TV Shows',
       'Docuseries, TV Comedies',
       'Comedies, Romantic Movies, Sports Movies',
       'TV Action & Adventure, TV Comedies, TV Dramas',
       'Children & Family Movies, Dramas, Sports Movies',
       'Action & Adventure, Dramas, Independent Movies',
       'Spanish-Language TV Shows, TV Dramas', 'Dramas, LGBTQ Movies',
       'TV Horror, TV Mysteries, TV Sci-Fi & Fantasy',
       'Action & Adventure, Dramas, Faith & Spirituality',
       'International TV Shows, TV Mysteries, TV Thrillers',
       'British TV Shows, Classic & Cult TV, International TV Shows',
       'Action & Adventure, Comedies, Independent Movies',
       'Music & Musicals', "British TV Shows, Kids' TV, TV Comedies",
       'Docuseries, Spanish-Language TV Shows',
       'Dramas, Independent Movies, Sports Movies',
       'TV Dramas, TV Mysteries, TV Thrillers',
       'Comedies, LGBTQ Movies, Music & Musicals',
       'International TV Shows, TV Action & Adventure, TV Mysteries',
       "Kids' TV, TV Comedies, Teen TV Shows",
       'International TV Shows, TV Dramas, TV Horror',
       'Comedies, International Movies, Thrillers',
       'Classic & Cult TV, TV Action & Adventure, TV Sci-Fi & Fantasy',
       'International TV Shows, TV Horror, TV Mysteries',
       'Children & Family Movies, Documentaries',
       'Music & Musicals, Romantic Movies', 'Romantic Movies',
       'Children & Family Movies, Classic Movies, Comedies',
       'TV Action & Adventure, TV Dramas',
       'Dramas, LGBTQ Movies, Romantic Movies',
       'Children & Family Movies, Comedies, Romantic Movies',
       'Comedies, Sports Movies', 'International Movies',
       'International TV Shows, Romantic TV Shows, TV Mysteries',
       'Stand-Up Comedy & Talk Shows',
       'Action & Adventure, International Movies, Romantic Movies',
       'Reality TV, TV Comedies',
       'Cult Movies, Dramas, International Movies', "Kids' TV, TV Dramas",
       'Crime TV Shows, International TV Shows, TV Mysteries',
       'Action & Adventure, Sci-Fi & Fantasy, Sports Movies',
       'TV Dramas, TV Sci-Fi & Fantasy, TV Thrillers',
       'Romantic TV Shows, TV Dramas, TV Sci-Fi & Fantasy',
       'Docuseries, TV Sci-Fi & Fantasy',
       'Anime Features, International Movies',
       "British TV Shows, Classic & Cult TV, Kids' TV",
       'British TV Shows, Reality TV, Romantic TV Shows',
       'Documentaries, Faith & Spirituality, International Movies',
       "Kids' TV, Reality TV, TV Dramas", 'LGBTQ Movies, Thrillers',
       'TV Action & Adventure, TV Mysteries, TV Sci-Fi & Fantasy',
       'Reality TV, Science & Nature TV',
       "Kids' TV, TV Action & Adventure, TV Comedies",
       'International TV Shows, Romantic TV Shows, TV Action & Adventure',
       'Children & Family Movies, Dramas, Independent Movies',
       'Comedies, Music & Musicals, Romantic Movies',
       'International TV Shows, Korean TV Shows, Reality TV',
       'Classic & Cult TV, TV Dramas, TV Sci-Fi & Fantasy',
       'Anime Features, Children & Family Movies',
       'Action & Adventure, International Movies, Sci-Fi & Fantasy',
       'Crime TV Shows, TV Action & Adventure, TV Dramas',
       'Classic & Cult TV, TV Action & Adventure, TV Horror',
       'International TV Shows, Korean TV Shows, TV Dramas',
       'International TV Shows, TV Action & Adventure, TV Horror',
       'Action & Adventure, Comedies, Romantic Movies',
       'International TV Shows, Korean TV Shows, TV Action & Adventure',
       "Classic & Cult TV, Kids' TV, TV Action & Adventure",
       'Anime Series, International TV Shows, TV Horror',
       'International TV Shows, Korean TV Shows, TV Horror',
       'Children & Family Movies, Comedies, International Movies',
       'International Movies, Sci-Fi & Fantasy',
       'International Movies, Sci-Fi & Fantasy, Thrillers',
       'Children & Family Movies, Dramas, Romantic Movies',
       'Anime Series, Romantic TV Shows',
       'Comedies, Dramas, LGBTQ Movies',
       'British TV Shows, International TV Shows, TV Action & Adventure',
       'Docuseries, Science & Nature TV, TV Comedies',
       'International TV Shows, Stand-Up Comedy & Talk Shows, TV Comedies',
       'Children & Family Movies, Dramas, Music & Musicals',
       'Action & Adventure, Independent Movies, International Movies',
       'Action & Adventure, Children & Family Movies, Sci-Fi & Fantasy',
       'Horror Movies, Independent Movies, Sci-Fi & Fantasy',
       'TV Dramas, TV Sci-Fi & Fantasy, Teen TV Shows',
       'Anime Features, International Movies, Sci-Fi & Fantasy',
       'Dramas, Independent Movies, Music & Musicals',
       "Kids' TV, TV Comedies, TV Dramas",
       'Children & Family Movies, Documentaries, Sports Movies',
       'Independent Movies, Sci-Fi & Fantasy, Thrillers',
       'Anime Features, Music & Musicals, Sci-Fi & Fantasy',
       'TV Comedies, TV Dramas, TV Sci-Fi & Fantasy',
       'Crime TV Shows, TV Action & Adventure',
       'Comedies, Faith & Spirituality, Romantic Movies',
       "Kids' TV, TV Action & Adventure",
       'Action & Adventure, Independent Movies',
       'International TV Shows, Reality TV, TV Comedies',
       'Docuseries, Reality TV, Teen TV Shows',
       'Crime TV Shows, International TV Shows, Reality TV',
       'Anime Series, Teen TV Shows',
       'Crime TV Shows, Romantic TV Shows, TV Dramas',
       'Anime Features, Romantic Movies',
       'Horror Movies, Sci-Fi & Fantasy, Thrillers',
       'International TV Shows, TV Comedies, TV Sci-Fi & Fantasy',
       'International TV Shows, Romantic TV Shows',
       'Anime Features, Music & Musicals',
       'Anime Features, International Movies, Romantic Movies',
       'International TV Shows, Romantic TV Shows, Teen TV Shows',
       'Docuseries, Stand-Up Comedy & Talk Shows',
       'Horror Movies, Independent Movies, Thrillers',
       'TV Action & Adventure, TV Comedies, TV Horror',
       'Documentaries, Stand-Up Comedy',
       "Kids' TV, Spanish-Language TV Shows",
       "British TV Shows, Kids' TV, TV Thrillers",
       "Kids' TV, TV Action & Adventure, TV Dramas",
       'Anime Series, Crime TV Shows',
       'Dramas, Sci-Fi & Fantasy, Thrillers',
       'TV Comedies, TV Dramas, TV Horror',
       'Children & Family Movies, Comedies, LGBTQ Movies',
       'International TV Shows, TV Action & Adventure, TV Sci-Fi & Fantasy',
       'Docuseries, TV Dramas',
       'Horror Movies, International Movies, Romantic Movies',
       'Crime TV Shows, Docuseries, Science & Nature TV',
       'International Movies, Music & Musicals, Thrillers',
       "Kids' TV, Spanish-Language TV Shows, Teen TV Shows",

In [51]:
## Cleaning Duration Column
df['duration'].head()

0       90 min
1    2 Seasons
2     1 Season
3     1 Season
4    2 Seasons
Name: duration, dtype: object

In [53]:
movies = df[df['type']=='Movie'].copy()

In [54]:
movies = df[df['type']=='Movie'].copy()

In [55]:
movies.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...

In [57]:
## Value Counts
df['type'].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [58]:
df['rating'].value_counts()

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NC-17          3
UR             3
74 min         1
84 min         1
66 min         1
Name: count, dtype: int64

In [59]:
df['country'].value_counts()

country
United States                                    2818
India                                             972
United Kingdom                                    419
Japan                                             245
South Korea                                       199
                                                 ...
Russia, Spain                                       1
Croatia, Slovenia, Serbia, Montenegro               1
Japan, Canada                                       1
United States, France, South Korea, Indonesia       1
United Arab Emirates, Jordan                        1
Name: count, Length: 748, dtype: int64

In [60]:
df['country'].value_counts().head(10)

country
United States     2818
India              972
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Egypt              106
Name: count, dtype: int64

In [63]:
## Save Cleaned Dataset
df.to_csv(
    'netflix_cleaned.csv',
    index=False
)

In [65]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added         0
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [70]:
df['director'] = df['director'].fillna('Unknown')

df['cast'] = df['cast'].fillna('Unknown')

df['country'] = df['country'].fillna('Unknown')

df['rating'] = df['rating'].fillna('Unknown')

df['duration'] = df['duration'].fillna('Unknown')

In [71]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64